import {
  UserProfile,
  Organization,
  DebateEvent,
  Team,
  Speaker,
  Judge,
  DebateRound,
  DebateRoom,
  Ballot,
  Survey,
  SurveyResponse,
  AuditLog,
} from '../types';

export const INITIAL_ORGANIZATION: Organization = {
  id: 'org-ku-debate',
  name: 'Kenyatta University Debate Society',
  slug: 'ku-debate-society',
  type: 'University',
  membersCount: 142,
  eventsCount: 12,
  createdAt: '2025-01-15T08:00:00Z',
};

export const INITIAL_USER: UserProfile = {
  id: 'usr-superadmin-1',
  email: 'bravinvulimwa84@gmail.com',
  fullName: 'Bravin Vulimwa',
  role: 'Super Admin',
  organizationId: 'org-ku-debate',
  organizationName: 'Kenyatta University Debate Society',
  status: 'Active',
  lastActivity: 'Just now',
  createdAt: '2025-01-15T08:00:00Z',
};

export const INITIAL_USERS: UserProfile[] = [
  INITIAL_USER,
  {
    id: 'usr-organizer-1',
    email: 'm.karanja@ku.ac.ke',
    fullName: 'Dr. Mercy Karanja',
    role: 'Organizer',
    organizationId: 'org-ku-debate',
    organizationName: 'Kenyatta University Debate Society',
    status: 'Active',
    lastActivity: '12 mins ago',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'usr-judge-1',
    email: 'j.otieno@strathmore.edu',
    fullName: 'James Otieno',
    role: 'Judge',
    organizationId: 'org-ku-debate',
    organizationName: 'Kenyatta University Debate Society',
    status: 'Active',
    lastActivity: '45 mins ago',
    createdAt: '2025-02-10T14:30:00Z',
  },
  {
    id: 'usr-survey-1',
    email: 's.chebet@ku.ac.ke',
    fullName: 'Sarah Chebet',
    role: 'Organizer',
    organizationId: 'org-ku-debate',
    organizationName: 'Kenyatta University Debate Society',
    status: 'Active',
    lastActivity: '2 hours ago',
    createdAt: '2025-03-01T09:15:00Z',
  },
  {
    id: 'usr-judge-2',
    email: 'a.ndungutse@makerere.ac.ug',
    fullName: 'Amina Ndungutse',
    role: 'Judge',
    organizationId: 'org-ku-debate',
    organizationName: 'Kenyatta University Debate Society',
    status: 'Active',
    lastActivity: '1 day ago',
    createdAt: '2025-03-05T11:00:00Z',
  },
  {
    id: 'usr-viewer-1',
    email: 'observer@debateligue.org',
    fullName: 'Prof. David Wanjala',
    role: 'Viewer',
    organizationId: 'org-ku-debate',
    organizationName: 'Kenyatta University Debate Society',
    status: 'Active',
    lastActivity: '3 days ago',
    createdAt: '2025-03-12T16:20:00Z',
  },
];

export const INITIAL_EVENTS: DebateEvent[] = [
  {
    id: 'evt-nudc-2026',
    organizationId: 'org-ku-debate',
    name: 'National Universities Debate Championship 2026',
    description: 'The premier national university debate tournament featuring teams across East Africa.',
    format: 'British Parliamentary',
    status: 'Live',
    startDate: '2026-08-08',
    endDate: '2026-08-12',
    venue: 'Main Auditorium, Kenyatta University',
    roundsCount: 5,
    currentRound: 3,
    maxSpeakersPerTeam: 2,
    scoringSystem: 'Standard 100-Point BP Scale',
    teamsCount: 16,
    speakersCount: 32,
    judgesCount: 12,
    isResultsPublished: false,
    createdAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'evt-inter-uni-2026',
    organizationId: 'org-ku-debate',
    name: 'Inter-University Debate Series Round 1',
    description: 'Quarterly inter-university competitive debate series.',
    format: 'World Schools',
    status: 'Upcoming',
    startDate: '2026-09-15',
    endDate: '2026-09-17',
    venue: 'Strathmore University Conference Center',
    roundsCount: 4,
    currentRound: 1,
    maxSpeakersPerTeam: 3,
    scoringSystem: 'World Schools 100-Point Scale',
    teamsCount: 12,
    speakersCount: 36,
    judgesCount: 8,
    isResultsPublished: false,
    createdAt: '2026-07-10T12:00:00Z',
  },
  {
    id: 'evt-east-africa-open-2025',
    organizationId: 'org-ku-debate',
    name: 'East Africa Open Debate Championship 2025',
    description: 'International invitation debate open held annually.',
    format: 'British Parliamentary',
    status: 'Completed',
    startDate: '2025-11-20',
    endDate: '2025-11-24',
    venue: 'Kenyatta International Convention Centre',
    roundsCount: 6,
    currentRound: 6,
    maxSpeakersPerTeam: 2,
    scoringSystem: 'Standard 100-Point BP Scale',
    teamsCount: 24,
    speakersCount: 48,
    judgesCount: 18,
    isResultsPublished: true,
    createdAt: '2025-09-01T09:00:00Z',
  },
];

export const INITIAL_ROUNDS: DebateRound[] = [
  {
    id: 'rnd-nudc-r1',
    eventId: 'evt-nudc-2026',
    roundNumber: 1,
    name: 'Round 1: Economic Policy',
    motion: 'This House would impose a global minimum corporate tax rate on tech multinationals.',
    infoSlide: 'Multinational tech companies currently utilize transfer pricing and tax havens to minimize tax liability in developing markets.',
    startTime: '2026-08-09T09:00:00Z',
    status: 'Complete',
    roomsCount: 4,
    completedRoomsCount: 4,
  },
  {
    id: 'rnd-nudc-r2',
    eventId: 'evt-nudc-2026',
    roundNumber: 2,
    name: 'Round 2: Environmental Governance',
    motion: 'This House believes that developing nations should prioritize industrial output over strict international climate compliance.',
    infoSlide: '',
    startTime: '2026-08-09T14:00:00Z',
    status: 'Complete',
    roomsCount: 4,
    completedRoomsCount: 4,
  },
  {
    id: 'rnd-nudc-r3',
    eventId: 'evt-nudc-2026',
    roundNumber: 3,
    name: 'Round 3: Artificial Intelligence & Ethics',
    motion: 'This House would mandate public ownership of foundational artificial intelligence models trained on public domain knowledge.',
    infoSlide: 'Foundational models refer to large generative models trained on web-scale public text and media datasets.',
    startTime: '2026-08-10T10:00:00Z',
    status: 'In Progress',
    roomsCount: 4,
    completedRoomsCount: 2,
  },
  {
    id: 'rnd-nudc-r4',
    eventId: 'evt-nudc-2026',
    roundNumber: 4,
    name: 'Round 4: International Security',
    motion: 'This House would grant permanent veto seats on the UN Security Council to regional economic unions.',
    infoSlide: '',
    startTime: '2026-08-10T15:00:00Z',
    status: 'Draft',
    roomsCount: 4,
    completedRoomsCount: 0,
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'tm-ku-a',
    eventId: 'evt-nudc-2026',
    name: 'Kenyatta Alpha',
    institution: 'Kenyatta University',
    category: 'Open',
    speakers: [],
    wins: 2,
    losses: 0,
    draws: 0,
    totalPoints: 162.5,
    speakerPoints: 325.0,
    rank: 1,
    status: 'Active',
  },
  {
    id: 'tm-strath-a',
    eventId: 'evt-nudc-2026',
    name: 'Strathmore Innovators',
    institution: 'Strathmore University',
    category: 'Open',
    speakers: [],
    wins: 2,
    losses: 0,
    draws: 0,
    totalPoints: 160.0,
    speakerPoints: 320.0,
    rank: 2,
    status: 'Active',
  },
  {
    id: 'tm-uon-a',
    eventId: 'evt-nudc-2026',
    name: 'Nairobi Jurists',
    institution: 'University of Nairobi',
    category: 'Open',
    speakers: [],
    wins: 1,
    losses: 1,
    draws: 0,
    totalPoints: 156.0,
    speakerPoints: 312.0,
    rank: 3,
    status: 'Active',
  },
  {
    id: 'tm-mak-a',
    eventId: 'evt-nudc-2026',
    name: 'Makerere Scholars',
    institution: 'Makerere University',
    category: 'ESL',
    speakers: [],
    wins: 1,
    losses: 1,
    draws: 0,
    totalPoints: 154.5,
    speakerPoints: 309.0,
    rank: 4,
    status: 'Active',
  },
  {
    id: 'tm-egerton-a',
    eventId: 'evt-nudc-2026',
    name: 'Egerton Advocates',
    institution: 'Egerton University',
    category: 'Novice',
    speakers: [],
    wins: 0,
    losses: 2,
    draws: 0,
    totalPoints: 148.0,
    speakerPoints: 296.0,
    rank: 5,
    status: 'Active',
  },
  {
    id: 'tm-jkuat-a',
    eventId: 'evt-nudc-2026',
    name: 'JKUAT Engineers',
    institution: 'JKUAT',
    category: 'Novice',
    speakers: [],
    wins: 0,
    losses: 2,
    draws: 0,
    totalPoints: 145.0,
    speakerPoints: 290.0,
    rank: 6,
    status: 'Active',
  },
];

export const INITIAL_SPEAKERS: Speaker[] = [
  {
    id: 'spk-1',
    teamId: 'tm-ku-a',
    teamName: 'Kenyatta Alpha',
    eventId: 'evt-nudc-2026',
    name: 'Kevin Mutua',
    email: 'k.mutua@students.ku.ac.ke',
    institution: 'Kenyatta University',
    category: 'Open',
    totalPoints: 163.5,
    averageScore: 81.75,
    highestScore: 83.0,
    roundsDebated: 2,
    rank: 1,
  },
  {
    id: 'spk-2',
    teamId: 'tm-ku-a',
    teamName: 'Kenyatta Alpha',
    eventId: 'evt-nudc-2026',
    name: 'Brenda Achieng',
    email: 'b.achieng@students.ku.ac.ke',
    institution: 'Kenyatta University',
    category: 'Open',
    totalPoints: 161.5,
    averageScore: 80.75,
    highestScore: 82.0,
    roundsDebated: 2,
    rank: 2,
  },
  {
    id: 'spk-3',
    teamId: 'tm-strath-a',
    teamName: 'Strathmore Innovators',
    eventId: 'evt-nudc-2026',
    name: 'Daniel Kipchirchir',
    email: 'd.kipchirchir@strathmore.edu',
    institution: 'Strathmore University',
    category: 'Open',
    totalPoints: 161.0,
    averageScore: 80.5,
    highestScore: 81.5,
    roundsDebated: 2,
    rank: 3,
  },
  {
    id: 'spk-4',
    teamId: 'tm-strath-a',
    teamName: 'Strathmore Innovators',
    eventId: 'evt-nudc-2026',
    name: 'Faith Wanjiru',
    email: 'f.wanjiru@strathmore.edu',
    institution: 'Strathmore University',
    category: 'Open',
    totalPoints: 159.0,
    averageScore: 79.5,
    highestScore: 80.5,
    roundsDebated: 2,
    rank: 4,
  },
  {
    id: 'spk-5',
    teamId: 'tm-uon-a',
    teamName: 'Nairobi Jurists',
    eventId: 'evt-nudc-2026',
    name: 'Emmanuel Omondi',
    email: 'e.omondi@uonbi.ac.ke',
    institution: 'University of Nairobi',
    category: 'Open',
    totalPoints: 157.0,
    averageScore: 78.5,
    highestScore: 79.0,
    roundsDebated: 2,
    rank: 5,
  },
  {
    id: 'spk-6',
    teamId: 'tm-mak-a',
    teamName: 'Makerere Scholars',
    eventId: 'evt-nudc-2026',
    name: 'Joan Akello',
    email: 'j.akello@makerere.ac.ug',
    institution: 'Makerere University',
    category: 'ESL',
    totalPoints: 155.5,
    averageScore: 77.75,
    highestScore: 78.5,
    roundsDebated: 2,
    rank: 6,
  },
];

export const INITIAL_JUDGES: Judge[] = [
  {
    id: 'jdg-1',
    eventId: 'evt-nudc-2026',
    name: 'James Otieno',
    email: 'j.otieno@strathmore.edu',
    institution: 'Strathmore University',
    experienceLevel: 'Chair',
    rating: 9.2,
    assignedRounds: 3,
    ballotsSubmitted: 2,
    status: 'In Progress',
  },
  {
    id: 'jdg-2',
    eventId: 'evt-nudc-2026',
    name: 'Amina Ndungutse',
    email: 'a.ndungutse@makerere.ac.ug',
    institution: 'Makerere University',
    experienceLevel: 'Chair',
    rating: 8.8,
    assignedRounds: 3,
    ballotsSubmitted: 3,
    status: 'Completed',
  },
  {
    id: 'jdg-3',
    eventId: 'evt-nudc-2026',
    name: 'Dr. Mercy Karanja',
    email: 'm.karanja@ku.ac.ke',
    institution: 'Kenyatta University',
    experienceLevel: 'Chair',
    rating: 9.5,
    assignedRounds: 3,
    ballotsSubmitted: 2,
    status: 'Assigned',
  },
  {
    id: 'jdg-4',
    eventId: 'evt-nudc-2026',
    name: 'Brian Kiptoo',
    email: 'b.kiptoo@egerton.ac.ke',
    institution: 'Egerton University',
    experienceLevel: 'Panelist',
    rating: 7.8,
    assignedRounds: 2,
    ballotsSubmitted: 2,
    status: 'Available',
  },
  {
    id: 'jdg-5',
    eventId: 'evt-nudc-2026',
    name: 'Cynthia Mwangi',
    email: 'c.mwangi@uonbi.ac.ke',
    institution: 'University of Nairobi',
    experienceLevel: 'Trainee',
    rating: 6.9,
    assignedRounds: 2,
    ballotsSubmitted: 1,
    status: 'Available',
  },
];

export const INITIAL_ROOMS: DebateRoom[] = [
  {
    id: 'rm-101',
    roundId: 'rnd-nudc-r3',
    eventId: 'evt-nudc-2026',
    roomName: 'Hall A (Science Complex)',
    governmentTeamId: 'tm-ku-a',
    governmentTeamName: 'Kenyatta Alpha',
    oppositionTeamId: 'tm-strath-a',
    oppositionTeamName: 'Strathmore Innovators',
    assignedJudges: [INITIAL_JUDGES[0]],
    status: 'Awaiting Ballots',
    expectedBallots: 1,
    submittedBallots: 0,
  },
  {
    id: 'rm-102',
    roundId: 'rnd-nudc-r3',
    eventId: 'evt-nudc-2026',
    roomName: 'Hall B (Law Block)',
    governmentTeamId: 'tm-uon-a',
    governmentTeamName: 'Nairobi Jurists',
    oppositionTeamId: 'tm-mak-a',
    oppositionTeamName: 'Makerere Scholars',
    assignedJudges: [INITIAL_JUDGES[1]],
    status: 'Complete',
    winnerTeamId: 'tm-uon-a',
    expectedBallots: 1,
    submittedBallots: 1,
  },
  {
    id: 'rm-103',
    roundId: 'rnd-nudc-r3',
    eventId: 'evt-nudc-2026',
    roomName: 'Room 204 (Humanities)',
    governmentTeamId: 'tm-egerton-a',
    governmentTeamName: 'Egerton Advocates',
    oppositionTeamId: 'tm-jkuat-a',
    oppositionTeamName: 'JKUAT Engineers',
    assignedJudges: [INITIAL_JUDGES[2]],
    status: 'In Progress',
    expectedBallots: 1,
    submittedBallots: 0,
  },
];

export const INITIAL_BALLOTS: Ballot[] = [
  {
    id: 'blt-102-1',
    debateRoomId: 'rm-102',
    eventId: 'evt-nudc-2026',
    roundNumber: 3,
    judgeId: 'jdg-2',
    judgeName: 'Amina Ndungutse',
    winningTeamId: 'tm-uon-a',
    governmentTotalPoints: 157.0,
    oppositionTotalPoints: 154.5,
    speakerScores: [
      {
        speakerId: 'spk-5',
        speakerName: 'Emmanuel Omondi',
        teamId: 'tm-uon-a',
        scores: { matter: 39.5, manner: 39.0 },
        totalScore: 78.5,
      },
      {
        speakerId: 'spk-6',
        speakerName: 'Joan Akello',
        teamId: 'tm-mak-a',
        scores: { matter: 38.5, manner: 38.5 },
        totalScore: 77.0,
      },
    ],
    strengthsComment: 'Government provided robust economic framing regarding tech monopolies and taxation mechanisms.',
    improvementsComment: 'Opposition should directly challenge the enforcement feasibility in cross-border jurisdictions.',
    generalComments: 'High standard of debate with clear engagement from both sides.',
    isLocked: true,
    submittedAt: '2026-08-10T11:15:00Z',
    status: 'Verified',
  },
];

export const INITIAL_SURVEYS: Survey[] = [
  {
    id: 'srv-nudc-feedback',
    organizationId: 'org-ku-debate',
    eventId: 'evt-nudc-2026',
    title: 'NUDC 2026 Participant Experience & Adjudication Quality',
    description: 'Help us evaluate motion balance, adjudication consistency, and venue organization.',
    status: 'Published',
    responsesCount: 48,
    completionRate: 92.5,
    averageTimeMinutes: 3.4,
    publicId: 'nudc2026-feedback',
    createdAt: '2026-08-08T10:00:00Z',
    updatedAt: '2026-08-09T18:00:00Z',
    questions: [
      {
        id: 'q1',
        type: 'Rating',
        title: 'Overall Tournament Organization Rating',
        description: 'Rate venue quality, schedule adherence, and promptness of pairings.',
        isRequired: true,
        ratingMax: 5,
      },
      {
        id: 'q2',
        type: 'Single choice',
        title: 'Primary Role in Competition',
        isRequired: true,
        options: ['Debater', 'Adjudicator / Judge', 'Institutional Observer', 'Organizing Committee'],
      },
      {
        id: 'q3',
        type: 'Likert scale',
        title: 'Motion Balance & Fair Adjudication Assessment',
        description: 'Indicate your level of agreement with the following statements.',
        isRequired: true,
        likertScale: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'],
      },
      {
        id: 'q4',
        type: 'Yes/No',
        title: 'Did you experience any technical or scheduling delays in your rounds?',
        isRequired: true,
      },
      {
        id: 'q5',
        type: 'Long text',
        title: 'What specific suggestions do you have for improving future rounds or adjudication feedback?',
        isRequired: false,
        conditionalLogic: {
          dependsOnQuestionId: 'q4',
          operator: 'equals',
          value: 'Yes',
        },
      },
    ],
  },
  {
    id: 'srv-debate-participation',
    organizationId: 'org-ku-debate',
    title: 'University Student Debate Engagement Study',
    description: 'Investigating factors influencing university debate club participation and retention.',
    status: 'Published',
    responsesCount: 112,
    completionRate: 88.0,
    averageTimeMinutes: 4.1,
    publicId: 'student-engagement-2026',
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-08-01T12:00:00Z',
    questions: [
      {
        id: 'sq1',
        type: 'Dropdown',
        title: 'Year of Study',
        isRequired: true,
        options: ['First Year', 'Second Year', 'Third Year', 'Fourth Year / Postgraduate'],
      },
      {
        id: 'sq2',
        type: 'Multiple choice',
        title: 'What factors motivate you to participate in debates?',
        isRequired: true,
        options: ['Public speaking skills', 'Critical thinking', 'Networking', 'Career preparation', 'Intellectual interest'],
      },
      {
        id: 'sq3',
        type: 'Long text',
        title: 'What barriers prevent you or your peers from attending weekly debate sessions?',
        isRequired: false,
      },
    ],
  },
];

export const INITIAL_SURVEY_RESPONSES: SurveyResponse[] = [
  {
    id: 'rsp-1',
    surveyId: 'srv-nudc-feedback',
    answers: {
      q1: 5,
      q2: 'Debater',
      q3: 'Agree',
      q4: 'No',
    },
    submittedAt: '2026-08-09T18:30:00Z',
    timeSpentSeconds: 195,
  },
  {
    id: 'rsp-2',
    surveyId: 'srv-nudc-feedback',
    answers: {
      q1: 4,
      q2: 'Adjudicator / Judge',
      q3: 'Strongly Agree',
      q4: 'Yes',
      q5: 'Clearer timing signals during rebuttal speeches would be helpful.',
    },
    submittedAt: '2026-08-09T19:10:00Z',
    timeSpentSeconds: 240,
  },
  {
    id: 'rsp-3',
    surveyId: 'srv-nudc-feedback',
    answers: {
      q1: 4,
      q2: 'Debater',
      q3: 'Agree',
      q4: 'Yes',
      q5: 'Audio quality in Law Block Hall B could be improved for judges at the back.',
    },
    submittedAt: '2026-08-10T08:15:00Z',
    timeSpentSeconds: 210,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-101',
    timestamp: '2026-08-10T11:15:05Z',
    actorEmail: 'a.ndungutse@makerere.ac.ug',
    actorRole: 'Judge',
    action: 'BALLOT_SUBMITTED',
    resource: 'Debate Room: Hall B (Law Block)',
    details: 'Submitted verified ballot for Round 3 (NUDC 2026). Ballot locked.',
    result: 'Success',
  },
  {
    id: 'log-100',
    timestamp: '2026-08-10T10:00:00Z',
    actorEmail: 'bravinvulimwa84@gmail.com',
    actorRole: 'Organization Admin',
    action: 'ROUND_STARTED',
    resource: 'Round 3: AI & Ethics',
    details: 'Initiated Round 3 pairings and opened room ballots.',
    result: 'Success',
  },
  {
    id: 'log-099',
    timestamp: '2026-08-09T14:05:00Z',
    actorEmail: 'm.karanja@ku.ac.ke',
    actorRole: 'Organizer',
    action: 'PAIRINGS_RELEASED',
    resource: 'Round 2: Environmental Governance',
    details: 'Published debate room assignments and judge pairings.',
    result: 'Success',
  },
  {
    id: 'log-098',
    timestamp: '2026-08-08T10:15:00Z',
    actorEmail: 'bravinvulimwa84@gmail.com',
    actorRole: 'Organization Admin',
    action: 'EVENT_STATUS_CHANGED',
    resource: 'National Universities Debate Championship 2026',
    details: 'Status changed from Upcoming to Live.',
    result: 'Success',
  },
];
