import type { VercelRequest, VercelResponse } from "@vercel/node";

// @ts-ignore -- generated by the configured build command.
import serverBundle from "../dist/server.cjs";
const { app } = serverBundle;

// Catch all API paths so Express receives /api/auth/login and every other API route.
export default function handler(req: VercelRequest, res: VercelResponse) {
  return app(req, res);
}
