import type { VercelRequest, VercelResponse } from "@vercel/node";

// `npm run build` creates this CommonJS server bundle before Vercel packages
// functions. Requiring it from here makes the bundle traceable at runtime;
// importing the root TypeScript source leaves an unresolved `/var/task/server`
// import in Vercel's generated function.
// @ts-ignore -- generated by the configured build command.
import serverBundle from "../dist/server.cjs";
const { app } = serverBundle;

export default function handler(req: VercelRequest, res: VercelResponse) {
	return app(req, res);
}
